# generated by datamodel-codegen:
#   filename:  quiz_schema.json
#   timestamp: 2024-04-09T05:18:24+00:00

from __future__ import annotations

from typing import List

from langchain_core.pydantic_v1 import BaseModel,Field, conlist



# class Model(BaseModel):
#     video: Video
#     quiz: Quiz
#     blank: Blank
#     code_python: CodePython
#     code_html: CodeHtml
#     code_css: CodeCss
#     code_javascript: CodeJavascript
#     code_html_css_javascript: CodeHtmlCssJavascript = Field(
#         ..., alias='code_html-css-javascript'
#     )
#     blank_code: BlankCode
#     lecture: Lecture
